name: Deploy

on: 
  push:
    branches: [main]

# permission for creating a package
permissions:
  contents: read
  packages: write

env:
  # it MUST contain start with ghcr.io/ and it MUST be lowercase
  IMAGE: ghcr.io/${{ github.repository_owner }}/portfolio-api
  VERSION: 0.1.${{ github.run_number }}
  CONFIGURATION_FILE: /Data/projects/

jobs:
  docker_image:
    name: 🏗️ Create Docker image
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v5

      - name: ⚙️ Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.VERSION }}
          build-args: |
            CONFIGURATION_FILE=/data/configuration_prod.json
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Print image name
        run: |
          echo "### Docker image: ${{ env.IMAGE }}:${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY

  deploy:
    name: 🚀 Call deploy script
    runs-on: ubuntu-latest
    needs: docker_image
    steps:
      - name: Run server script
        run: |
          echo "Running deploy script for API service..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          
          # Call the deploy script on the server (adjust the script name as needed)
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} project-portfolio_deploy-api
          STATUS=$?
          rm ~/.ssh/id_rsa
          if [ $STATUS -ne 0 ]; then
            echo "ERROR: Remote deploy script failed with exit code $STATUS"
            exit $STATUS
          fi
